# * Copyright 2026 Lukas Spies <Lukas@photoqt.org>
# * SPDX-License-Identifier: GPL-2.0-or-later
name: photoqt
confinement: strict
grade: stable
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

adopt-info: photoqt

description: Fast and highly configurable image viewer with a simple and nice interface, supporting well over 100 file formats, including images, videos, and documents.
summary: View and manage images, videos, and documents.

contact: Lukas@photoqt.org
issues: https://gitlab.com/lspies/photoqt/-/issues
source-code: https://gitlab.com/lspies/photoqt
website: https://photoqt.org
donation: https://photoqt.org/donate

apps:
  photoqt:
    extensions:
      - kde-neon-6
    common-id: org.photoqt.PhotoQt
    desktop: usr/share/applications/org.photoqt.PhotoQt.desktop
    command: usr/bin/photoqt
    slots:
      - session-slot
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - x11
      - unity7
      - audio-playback
      - network
      - network-bind
      - cups
      - session-plug
      - ffmpeg-2404
    environment:
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH

compression: lzo

plugs:
  session-plug:
    interface: dbus
    bus: session
    name: org.photoqt.PhotoQt
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2404

slots:
  session-slot:
    interface: dbus
    bus: session
    name: org.photoqt.PhotoQt

parts:
  photoqt-extensions:
    plugin: cmake
    source: https://photoqt.org/downloads/extensions/photoqt-extensions-5.2.tar.gz
    parse-info:
      - usr/share/metainfo/org.photoqt.Extensions.metainfo.xml
    override-build: |
      ln -sf /usr/include/GraphicsMagick/Magick++ /usr/include/Magick++
      ln -sf /usr/include/GraphicsMagick/magick /usr/include/magick
      snapcraftctl build
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr/lib/PhotoQt/extensions
      - -DQT_QML_NO_CACHEGEN=ON
      - -DWITH_IMAGEMAGICK=OFF
      - -DWITH_GRAPHICSMAGICK=ON
    build-packages:
      - libexiv2-dev
      - libexpat1-dev
      - libheif-dev
      - libjpeg-dev
      - liblcms2-dev
      - libpng-dev
      - libtiff-dev
      - libraw-dev
      - libdevil-dev
      - libgraphicsmagick++1-dev
      - libgraphicsmagick1-dev

  photoqt:
    plugin: cmake
    source: https://photoqt.org/downloads/source/photoqt-5.2.tar.gz
    parse-info:
      - usr/share/metainfo/org.photoqt.PhotoQt.metainfo.xml
    override-build: |
      ln -sf /usr/include/GraphicsMagick/Magick++ /usr/include/Magick++
      ln -sf /usr/include/GraphicsMagick/magick /usr/include/magick
      snapcraftctl build
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DQT_QML_NO_CACHEGEN=ON
      - -DWITH_IMAGEMAGICK=OFF
      - -DWITH_GRAPHICSMAGICK=ON
      - -DWITH_LIBRAW=ON
      - -DWITH_DEVIL=ON
      - -DWITH_POPPLER=OFF
      - -DWITH_QTPDF=ON
      - -DWITH_LIBARCHIVE=ON
      - -DWITH_VIDEO_QT=ON
      - -DWITH_VIDEO_MPV=OFF
      - -DWITH_LIBVIPS=OFF
      - -DWITH_RESVG=OFF
      - -DWITH_EXIV2=ON
      - -DWITH_EXIV2_ENABLE_BMFF=ON
      - -DWITH_PUGIXML=OFF
      - -DWITH_ZXING=ON
      - -DWITH_CHROMECAST=OFF
      - -DWITH_LOCATION=ON
      - -DWITH_LCMS2=ON
      - -DWITH_MOTIONPHOTO=ON
      - -DWITH_PHOTOSPHERE=ON
      - -DWITH_EXTENSIONS_SUPPORT=ON
    build-packages:
      - libexiv2-dev
      - libexpat1-dev
      - libheif-dev
      - libjpeg-dev
      - liblcms2-dev
      - libpng-dev
      - libtiff-dev
      - libxml2-dev
      - libraw-dev
      - libdevil-dev
      - libarchive-dev
      - libzxing-dev
      - libcups2-dev
      - libproxy1v5
      - libyaml-cpp-dev
      - libqca-qt6-dev
      - qt6-declarative-dev
      - libgraphicsmagick++1-dev
      - libgraphicsmagick1-dev
      - libproxy1v5
    stage-packages:
      - libheif1
      - libjpeg8
      - libjpeg-turbo8
      - libx265-199
      - kimageformat-plugins
      - ghostscript
      - libdevil1c2
      - libarchive13t64
      - libzxing3
      - libjxr0t64
      - libcups2t64
      - libyaml-cpp0.8
      - libqca-qt6-2
      - libqca-qt6-plugins
      - libglut3.12
      - libgraphicsmagick-q16-3t64
      - libgraphicsmagick++-q16-12t64
      - graphicsmagick
      - libpulse0
