# * Copyright 2026 Lukas Spies <Lukas@photoqt.org>
# * SPDX-License-Identifier: GPL-2.0-or-later
name: photoqt
confinement: strict
grade: stable
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

adopt-info: photoqt

description: Fast and highly configurable image viewer with a simple and nice interface, supporting well over 100 file formats, including images, videos, and documents.
summary: View and manage images, videos, and documents.

contact: Lukas@photoqt.org
issues: https://gitlab.com/lspies/photoqt/-/issues
source-code: https://gitlab.com/lspies/photoqt
website: https://photoqt.org
donation: https://photoqt.org/donate


apps:
  photoqt:
    extensions:
      - kde-neon-6
    common-id: org.photoqt.PhotoQt
    desktop: usr/local/share/applications/org.photoqt.PhotoQt.desktop
    command: usr/local/bin/photoqt
    slots:
      - session-slot
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - x11
      - unity7
      - audio-playback
      - network
      - network-bind
      - cups
      - session-plug
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy"

compression: lzo

plugs:
  session-plug:
    interface: dbus
    bus: session
    name: org.photoqt.PhotoQt

slots:
  session-slot:
    interface: dbus
    bus: session
    name: org.photoqt.PhotoQt

parts:
  imagemagick:
    plugin: autotools
    source: https://github.com/ImageMagick/ImageMagick
    source-type: git
    source-tag: 7.1.2-11
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-shared
      - --disable-static
      - --disable-docs
      - --with-modules
      - --with-threads
      - --with-png
      - --enable-hdri
      - --enable-opencl
      - --with-djvu
      - --with-fftw
      - --with-jxl
      - --with-lqr
      - --with-modules
      - --with-openexr
      - --with-openjp2
      - --with-rsvg
      - --with-webp
      - --with-wmf
      - --with-xml
      - --with-dps
      - --with-fpx
      - --with-gvc
    build-packages:
      - libheif-dev
      - libjpeg-dev
      - liblcms2-dev
      - libpng-dev
      - libtiff-dev
      - libxml2-dev
      - libraw-dev
      - libltdl-dev
    stage:
      - usr/lib/*

  photoqt-extensions:
    plugin: cmake
    source: https://photoqt.org/downloads/extensions/photoqt-extensions-5.1.tar.gz
    after:
      - imagemagick
    parse-info:
      - usr/local/share/metainfo/org.photoqt.Extensions.metainfo.xml
    override-build: |
      sed -i 's/ImageMagick::Magick++/\"imagemagick\"/g' $SNAPCRAFT_PART_SRC/CMakeLists.txt
      sed -i 's/ImageMagick::Magick++/\"imagemagick\"/g' $SNAPCRAFT_PART_SRC/*/CMakeLists.txt
      snapcraftctl build
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr/lib/PhotoQt/extensions
      - -DWITH_IMAGEMAGICK=ON
      - -DWITH_GRAPHICSMAGICK=OFF
    build-packages:
      - libexiv2-dev
      - libexpat1-dev
      - libheif-dev
      - libjpeg-dev
      - liblcms2-dev
      - libpng-dev
      - libtiff-dev
      - libraw-dev
      - libdevil-dev
      - libfreeimageplus-dev

  photoqt:
    plugin: cmake
    source: https://photoqt.org/downloads/source/photoqt-5.1.tar.gz
    after:
      - imagemagick
    parse-info:
      - usr/local/share/metainfo/org.photoqt.PhotoQt.metainfo.xml
    override-build: |
      sed -i 's/ImageMagick::Magick++/\"imagemagick\"/g' $SNAPCRAFT_PART_SRC/CMakeLists.txt
      snapcraftctl build
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_IMAGEMAGICK=ON
      - -DWITH_GRAPHICSMAGICK=OFF
      - -DWITH_LIBRAW=ON
      - -DWITH_DEVIL=ON
      - -DWITH_FREEIMAGE=ON
      - -DWITH_POPPLER=OFF
      - -DWITH_QTPDF=ON
      - -DWITH_LIBARCHIVE=ON
      - -DWITH_VIDEO_QT=ON
      - -DWITH_VIDEO_MPV=ON
      - -DWITH_LIBVIPS=OFF
      - -DWITH_RESVG=OFF
      - -DWITH_EXIV2=ON
      - -DWITH_EXIV2_ENABLE_BMFF=ON
      - -DWITH_PUGIXML=OFF
      - -DWITH_ZXING=ON
      - -DWITH_CHROMECAST=OFF
      - -DWITH_LOCATION=ON
      - -DWITH_LCMS2=ON
      - -DWITH_MOTIONPHOTO=ON
      - -DWITH_PHOTOSPHERE=ON
      - -DWITH_EXTENSIONS_SUPPORT=ON
    build-packages:
      - libexiv2-dev
      - libexpat1-dev
      - libheif-dev
      - libjpeg-dev
      - liblcms2-dev
      - libpng-dev
      - libtiff-dev
      - libxml2-dev
      - libraw-dev
      - libdevil-dev
      - libfreeimageplus-dev
      - libarchive-dev
      - libzxing-dev
      - libmpv-dev
      - libcups2-dev
      - libproxy1v5
      - libyaml-cpp-dev
      - libqca-qt6-dev
      - qt6-declarative-dev
    stage-packages:
      - libheif1
      - libjpeg8
      - libjpeg-turbo8
      - libx265-199
      - kimageformat-plugins
      - ghostscript
      - libdevil1c2
      - libfreeimage3
      - libarchive13t64
      - libzxing3
      - libmpv2
      - libjxr0t64
      - libcups2t64
      - libyaml-cpp0.8
      - libqca-qt6-2
      - libqca-qt6-plugins
      - libglut3.12
