# * Copyright 2024 Lukas Spies <Lukas@photoqt.org>
# * SPDX-License-Identifier: GPL-2.0-or-later
name: photoqt
confinement: strict
grade: stable
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

adopt-info: photoqt

description: Fast and highly configurable image viewer with a simple and nice interface, supporting well over 100 file formats, including images, videos, and documents.
summary: View and manage images, videos, and documents.

contact: Lukas@photoqt.org
issues: https://gitlab.com/lspies/photoqt/-/issues
source-code: https://gitlab.com/lspies/photoqt
website: https://photoqt.org
donation: https://photoqt.org/donate


apps:
  photoqt:
    extensions:
      - kde-neon-6
    common-id: org.photoqt.PhotoQt
    desktop: usr/local/share/applications/org.photoqt.PhotoQt.desktop
    command: usr/local/bin/photoqt
    slots:
      - session-slot
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - x11
      - unity7
      - audio-playback
      - network
      - network-bind
      - cups
      - session-plug
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy"

compression: lzo

plugs:
  session-plug:
    interface: dbus
    bus: session
    name: org.photoqt.PhotoQt

slots:
  session-slot:
    interface: dbus
    bus: session
    name: org.photoqt.PhotoQt

parts:
  photoqt:
    plugin: cmake
    source: https://photoqt.org/downloads/source/photoqt-4.9.2.tar.gz
    parse-info:
      - usr/local/share/metainfo/org.photoqt.PhotoQt.metainfo.xml
    override-build: |
      ln -sf /usr/include/GraphicsMagick/Magick++ /usr/include/Magick++
      ln -sf /usr/include/GraphicsMagick/magick /usr/include/magick
      sed -i 's/VERSION 3.26/VERSION 3.22/g' $SNAPCRAFT_PART_SRC/CMakeLists.txt
      snapcraftctl build
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_IMAGEMAGICK=OFF
      - -DWITH_GRAPHICSMAGICK=ON
      - -DWITH_LIBRAW=ON
      - -DWITH_DEVIL=ON
      - -DWITH_FREEIMAGE=ON
      - -DWITH_POPPLER=OFF
      - -DWITH_QTPDF=ON
      - -DWITH_LIBARCHIVE=ON
      - -DWITH_VIDEO_QT=ON
      - -DWITH_VIDEO_MPV=ON
      - -DWITH_LIBVIPS=OFF
      - -DWITH_RESVG=OFF
      - -DWITH_EXIV2=ON
      - -DWITH_EXIV2_ENABLE_BMFF=ON
      - -DWITH_PUGIXML=ON
      - -DWITH_ZXING=ON
      - -DWITH_CHROMECAST=OFF
      - -DWITH_LOCATION=ON
      - -DWITH_LCMS2=ON
      - -DWITH_MOTIONPHOTO=ON
      - -DWITH_PHOTOSPHERE=ON
    build-packages:
      - libexiv2-dev
      - libexpat1-dev
      - libheif-dev
      - libjpeg-dev
      - liblcms2-dev
      - libpng-dev
      - libtiff-dev
      - libxml2-dev
      - libraw-dev
      - libdevil-dev
      - libfreeimageplus-dev
      - libpugixml-dev
      - libarchive-dev
      - libzxing-dev
      - libmpv-dev
      - libgraphicsmagick++1-dev
      - libgraphicsmagick1-dev
      - libcups2-dev
      - libproxy1v5
    stage-packages:
      - libheif1
      - libjpeg8
      - libjpeg-turbo8
      - libx265-199
      - libgif7
      - kimageformat-plugins
      - libraw23t64
      - ghostscript
      - libdevil1c2
      - libfreeimage3
      - libpugixml1v5
      - libarchive13t64
      - libzxing3
      - libmpv2
      - libjxr0t64
      - libdjvulibre21
      - libgraphicsmagick-q16-3t64
      - libgraphicsmagick++-q16-12t64
      - graphicsmagick
      - libcups2t64
